version: '3.8'

services:
  # 文件服务
  file-service:
    build:
      context: ./shopping_file_service
      dockerfile: Dockerfile
    container_name: shopping-file-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 用户服务
  user-service:
    build:
      context: ./shopping_user_service
      dockerfile: Dockerfile
    container_name: shopping-user-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 用户API
  user-api:
    build:
      context: ./shopping_user_customer_api
      dockerfile: Dockerfile
    container_name: shopping-user-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 商品服务
  goods-service:
    build:
      context: ./shopping_goods_service
      dockerfile: Dockerfile
    container_name: shopping-goods-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 分类服务
  category-service:
    build:
      context: ./shopping_category_service
      dockerfile: Dockerfile
    container_name: shopping-category-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 分类API
  category-api:
    build:
      context: ./shopping_category_customer_api
      dockerfile: Dockerfile
    container_name: shopping-category-api
    restart: always
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 搜索服务
  search-service:
    build:
      context: ./shopping_search_service
      dockerfile: Dockerfile
    container_name: shopping-search-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 搜索API
  search-api:
    build:
      context: ./shopping_search_customer_api
      dockerfile: Dockerfile
    container_name: shopping-search-api
    restart: always
    ports:
      - "8083:8080"
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 购物车服务
  cart-service:
    build:
      context: ./shopping_cart_service
      dockerfile: Dockerfile
    container_name: shopping-cart-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 购物车API
  cart-api:
    build:
      context: ./shopping_cart_customer_api
      dockerfile: Dockerfile
    container_name: shopping-cart-api
    restart: always
    ports:
      - "8084:8080"
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 订单服务
  order-service:
    build:
      context: ./shopping_order_service
      dockerfile: Dockerfile
    container_name: shopping-order-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 订单API
  order-api:
    build:
      context: ./shopping_order_customer_api
      dockerfile: Dockerfile
    container_name: shopping-order-api
    restart: always
    ports:
      - "8085:8080"
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 支付服务
  pay-service:
    build:
      context: ./shopping_pay_service
      dockerfile: Dockerfile
    container_name: shopping-pay-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 秒杀服务
  seckill-service:
    build:
      context: ./shopping_seckill_service
      dockerfile: Dockerfile
    container_name: shopping-seckill-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 秒杀API
  seckill-api:
    build:
      context: ./shopping_seckill_customer_api
      dockerfile: Dockerfile
    container_name: shopping-seckill-api
    restart: always
    ports:
      - "8086:8080"
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 消息服务
  message-service:
    build:
      context: ./shopping_message_service
      dockerfile: Dockerfile
    container_name: shopping-message-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 推荐服务
  recommend-service:
    build:
      context: ./shopping_recommend_service
      dockerfile: Dockerfile
    container_name: shopping-recommend-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 推荐API
  recommend-api:
    build:
      context: ./shopping_recommend_api
      dockerfile: Dockerfile
    container_name: shopping-recommend-api
    restart: always
    ports:
      - "8087:8080"
    environment:
      - JAVA_OPTS=-server -Xms96m -Xmx192m
    deploy:
      resources:
        limits:
          memory: 250M

  # 管理员服务
  admin-service:
    build:
      context: ./shopping_admin_service
      dockerfile: Dockerfile
    container_name: shopping-admin-service
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M

  # 管理员API
  manager-api:
    build:
      context: ./shopping_manager_api
      dockerfile: Dockerfile
    container_name: shopping-manager-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx256m
    deploy:
      resources:
        limits:
          memory: 300M
