server:
  port: 8082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 118.178.88.182:8848
        namespace: public
        group: DEFAULT_GROUP
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        # 用户API路由
        - id: shopping-user-api
          uri: lb://shopping-user-customer-api
          predicates:
            - Path=/api/user/shoppingUser/**
          filters:
            - StripPrefix=1
        # 订单API路由
        - id: shopping-order-api
          uri: lb://shopping-order-customer-api
          predicates:
            - Path=/api/user/order/**
          filters:
            - StripPrefix=1
        # 购物车API路由
        - id: shopping-cart-api
          uri: lb://shopping-cart-customer-api
          predicates:
            - Path=/api/user/cart/**
          filters:
            - StripPrefix=1
        # 搜索API路由
        - id: shopping-search-api
          uri: lb://shopping-search-customer-api
          predicates:
            - Path=/api/user/goodsSearch/**
          filters:
            - StripPrefix=1
        # 分类API路由
        - id: shopping-category-api
          uri: lb://shopping-category-customer-api
          predicates:
            - Path=/api/user/category/**
          filters:
            - StripPrefix=1
        # 秒杀API路由
        - id: shopping-seckill-api
          uri: lb://shopping-seckill-customer-api
          predicates:
            - Path=/api/user/seckillGoods/**
          filters:
            - StripPrefix=1
        # 推荐API路由
        - id: shopping-recommend-api
          uri: lb://shopping-recommend-api
          predicates:
            - Path=/api/user/recommend/**
          filters:
            - StripPrefix=1
      
# Knife4j增强配置
knife4j:
  enable: true
  gateway:
    enabled: true
    strategy: manual
    discover:
      enabled: true
    routes:
      - name: 用户服务API文档
        url: /user/doc.html
        service-name: shopping-user-customer-api
        order: 1
      - name: 订单服务API文档
        url: /order/doc.html
        service-name: shopping-order-customer-api
        order: 2
      - name: 购物车服务API文档
        url: /cart/doc.html
        service-name: shopping-cart-customer-api
        order: 3
      - name: 搜索服务API文档
        url: /search/doc.html
        service-name: shopping-search-customer-api
        order: 4
      - name: 分类服务API文档
        url: /category/doc.html
        service-name: shopping-category-customer-api
        order: 5
      - name: 秒杀服务API文档
        url: /seckill/doc.html
        service-name: shopping-seckill-customer-api
        order: 6
      - name: 推荐服务API文档
        url: /recommend/doc.html
        service-name: shopping-recommend-api
        order: 7

# JWT配置
jwt:
  secret: "{\"kty\":\"RSA\",\"n\":\"z2VKUV1_UlpXNTGf2IqKLu1FQALM5V1_AidaJ9_ehAjNPQhtlTVKpbUZOznzKP66g54TUUQYMiDfwV3irf5qy2lDVi_B9iID8AtGUaFkV00jRYqwfSm1aQADFcAZ6nIi4YuofGHu31QLOB6FEg3KJve1LbOMwhDjPm1PBK0M_6DxsEAMpXeSz5XynRHcELwBl0l1pB0F8RA_6VbDGamyKJch3jFCMXxDdTWXfu3548vzXA3AAC5QORaxvR4h2qNvAWi3SL_W-6IFVDwFN0ODCO64TmAx3JxyQoq3LwAlqUOK2LAbFfRMXe1aMMtCCXFlg_4hRvoojNbuBMhoVJK_mQ\",\"e\":\"AQAB\",\"d\":\"OFslWTvHW8j5tpYwAecPipXmAfFg3RjNaPfpizlNnWJI5wNRx8BN8v5lh08FcMfbReWgCS6wRnrhYomRDce7HGATsKlUkv4GROXDa24oNoLbCUwZDkHVrl0W-YOUZz0xlklddMMl5mDPlaXRcij2HCWmgW8vWhK9tVp9pN8jT5jeOVqljgp779l7wvHf3F24LAjhakd3Um32z54sBfBXI2GpewEFcFQIn3BFW2djv1Q3_Lax6siN9K_4WpT53EP_EdkHgJXkLDPunbvuKi9eUxDWnP3AmF3ducAl1x_AwYIm7TAhU9NM9D3CCBLWCvmR45g1WDko2Rk0Y4Ti3aNm0w\",\"p\":\"0-Viv14-suAc6N-x7Kv4Wp3DxPBHWJ2oQC01U0L0yvz7VrMbjSTP6ETo19uoyx3kUS4kbYKgiu3AyQj687KhL6TrSmepVjjlquc4kPBq5PWnLzRg9yuRQ7M6MQsvftOlZ1r5z5Hww-jh59wydAINHcGpo49tTYV1HVr1_7mFmNs\",\"q\":\"-pAbnL-ilwjChbKgmsVSMEZ-Rfx3hLBQ4y9EyIn9B31c6y3sgkOk7qC8k2yppC3UnFKLPCUCqoCwps6j9gK4v-uqQ3omIAO3lyiSnFTasc5ggKxH0LzeKFVtd5EX-cwCXs_8zDeUSW-X7lybEwv2HkUg0gkUMIHLAWgEAwJGiZs\",\"dp\":\"yQAD_tHQme97nO9tILs0eAjFhtACba4HxvDbb6LJALCfXmvCC85KpeKQGQrV_-7YAKXLilHqJj9Hq6uoGXlt6vr-8vKIMDECs25oOxzD2XKo519BR9V9E4I1Bga9RApSEUu8QkkG4V_MwxsehOrZNEvbtjo8jde182Wwiqaacxc\",\"dq\":\"n9Z0Nt8syiplZMKZn4HGt1MQ1HaEi9mqD_MkbsVP64o2TzSBjmu2eB-DjIwh_8DYw0wI1DpL5BaqGg7yG0qLLqsYd2khjwSwBjZ0qFOdGxYrC4pbWbZSBerRJRgi8lAJJxCJFIFUEDCm_ACJUHIt9AtnL3VpMrRpmyEOhhjahIc\",\"qi\":\"eHzvG_E8-5W_xCCBnfEZJA1aP7BXT47AJm5hGRkcNkhYPxPZFfMfaXVhukHq-K13MFyc-eqk_U0Fn2U3Y-PakmFieJejRIWeBEQQqFS1oapimf-cpqTF4JJr1lHSzscFlD50mH7Ut-b1W5p4ld9p8_hhHTb2dCiWUZr0oB8LJfo\"}"
  ignore-paths: >
    /auth/login,
    /api/user/shoppingUser/loginPassword,
    /doc.html,
    /webjars/**,
    /swagger-resources/**,
    /doc.html/**,
    /v2/api-docs/**,
    /v3/api-docs/**,
    /swagger-ui.html,
    /swagger-ui/**,
    /**/doc.html/**,
    /*/doc.html/**,
    /user/doc.html/**,
    /order/doc.html/**,
    /cart/doc.html/**,
    /search/doc.html/**,
    /category/doc.html/**,
    /seckill/doc.html/**,
    /recommend/doc.html/**

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG